brew "act"
brew "asciinema"
brew "bottom"
brew "btop"
brew "ccache"
brew "cmake"
brew "cmatrix"
brew "colima"
brew "cowsay"
brew "deno"
brew "docker"
brew "docker-buildx"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "gh"
brew "git-delta"
brew "gitlab-runner"
brew "go"
brew "jq"
brew "lolcat"
brew "mas"
brew "maven"
brew "neovim"
brew "node"
brew "onefetch"
brew "qt"
brew "ripgrep"
brew "sbt"
brew "scala"
brew "sevenzip"
brew "sl"
brew "speedtest-cli"
brew "starship"
brew "stylua"
brew "uv"
brew "vapor"
brew "yt-dlp"
brew "coursier/formulas/coursier"
brew "fish-shell/fish-beta-4/fish"
brew "oven-sh/bun/bun"
cask "adguard"
cask "alt-tab"
cask "appcleaner"
cask "arc"
cask "chatgpt"
cask "chatterino"
cask "fluor"
cask "font-sf-mono-nerd-font-ligaturized"
cask "ghostty"
cask "gimp"
cask "grandperspective"
cask "maccy"
cask "mp3tag"
cask "openvpn-connect"
cask "rapidapi"
cask "raycast"
cask "scroll-reverser"
cask "sf-symbols"
cask "shottr"
cask "stats"
cask "subler"
cask "swish"
cask "vscodium"
cask "whatsapp"
cask "zen-browser"
mas "AudioBookBinder", id: 413969927
mas "AusweisApp", id: 948660805
mas "Craft", id: 1487937127
mas "DevCleaner", id: 1388020431
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
