#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        focused
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff00ff00
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  45
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# unmanaged applications
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Digital Colour Meter$" manage=off
yabai -m rule --add app="^War Thunder Launcher$" manage=off
yabai -m rule --add app="^Mullvad VPN$" manage=off
yabai -m rule --add app="^Glyphfinder$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^Paradox Launcher$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^TeamViewer$" manage=off
yabai -m rule --add app="^Simulator$" manage=off
yabai -m rule --add app="^Problem Reporter$" manage=off

# sticky applications
yabai -m rule --add app="^Digital Colour Meter$" sticky=on

# disable the finder file details popup from being managed
yabai -m rule --add app="^Finder$" title=".*Info$" manage=off
yabai -m rule --add app="^Finder$" title="^Copy$" manage=off
yabai -m rule --add app="^Finder$" title="^iCloud Progress$" manage=off
yabai -m rule --add app="^Finder$" title="^Chatterino2$" manage=off

# disable the safari preferences window from being managed
yabai -m rule --add app="^Safari$" title="^General$" manage=off
yabai -m rule --add app="^Safari$" title="^Tabs$" manage=off
yabai -m rule --add app="^Safari$" title="^AutoFill$" manage=off
yabai -m rule --add app="^Safari$" title="^Passwords$" manage=off
yabai -m rule --add app="^Safari$" title="^Search$" manage=off
yabai -m rule --add app="^Safari$" title="^Security$" manage=off
yabai -m rule --add app="^Safari$" title="^Privacy$" manage=off
yabai -m rule --add app="^Safari$" title="^Websites$" manage=off
yabai -m rule --add app="^Safari$" title="^Extensions$" manage=off
yabai -m rule --add app="^Safari$" title="^Advanced$" manage=off

# disable the discord updater popup from being managed while discord is starting
yabai -m rule --add app="^Discord$" title="^Discord Updater$" manage=off

yabai -m rule --add app="^Steam$" opacity=1.0

echo "yabai configuration loaded.."
